# Generated by Django 4.2 on 2023-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('img', models.FileField(upload_to='media/sketch/')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.FileField(max_length=3000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=2000)),
            ],
        ),
    ]
